--
-- PostgreSQL database dump
--

-- Dumped from database version 13.0 (Ubuntu 13.0-1.pgdg20.04+1)
-- Dumped by pg_dump version 13.0 (Ubuntu 13.0-1.pgdg20.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: CatalogItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CatalogItems" (
    "Id" bigint NOT NULL,
    "Name" text,
    "Description" text,
    "Price" numeric NOT NULL,
    "MainImageName" text
);


ALTER TABLE public."CatalogItems" OWNER TO postgres;

--
-- Name: CatalogItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CatalogItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CatalogItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: CatalogItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CatalogItems" ("Id", "Name", "Description", "Price", "MainImageName") FROM stdin;
3	Miecz 11	Bardzo potężny	11.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
4	Miecz 11	Bardzo potężny	11.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
1	Test 1	Test 1.Des	10.3	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
2	Test 2	Test 2.Des	12.3	bde1623e-fea1-43de-9385-32df9fab38f7.png
5	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
6	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
7	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
8	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
9	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
10	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
11	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
12	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
13	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
14	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
15	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
16	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
17	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
18	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
19	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
20	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
21	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
22	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
23	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
24	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
25	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
26	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
27	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
28	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
29	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
30	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
31	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
32	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
33	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
34	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
35	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
36	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
37	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
38	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
39	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
40	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
41	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
42	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
43	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
44	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
45	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
46	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
47	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
48	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
49	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
50	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
51	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
52	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
53	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
54	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
55	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
56	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
57	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
58	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
59	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
60	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
61	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
62	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
63	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
64	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
65	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
66	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
67	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
68	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
69	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
70	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
71	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
72	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
73	Miecz 1	Test	100.32	c28bda78-0830-4208-9fd6-c0419a97d0c7.png
74	Miecz 1	Test	100.32	7208570c-4504-42f3-80a0-f33870ab1dc0.png
75	Miecz 1	Test	100.32	0123ba85-22bd-4b5d-aaeb-c5efeced1f33.png
76	Miecz 1	Test	100.32	bde1623e-fea1-43de-9385-32df9fab38f7.png
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20201018091029_InitialCreate	3.1.9
20201021191423_MainImageNameInCatalogItem	3.1.9
20201024101959_ChangeGuidToStringInCatalogItem	3.1.9
\.


--
-- Name: CatalogItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CatalogItems_Id_seq"', 76, true);


--
-- Name: CatalogItems PK_CatalogItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CatalogItems"
    ADD CONSTRAINT "PK_CatalogItems" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

